### PR TITLE
Parse .NET/CLR headers and metadata

### LINKED ISSUE #223: parse the .NET Directory
Parse the IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR directory.  It is also known as the .NET directory: http://www.ntcore.com/files/dotnetformat.htm

### PR DESCRIPTION
**Pull request by malwarefrank**
Fixes #223

### CODE REVIEW

**Comment by malwarefrank** [comment]
This is a large addition because .NET/CLR files are essentially new file formats built on top of PE32.  If this is outside the scope of your project, let me know and I will make this into its own project that uses pefile.

**Comment by malwarefrank** [comment]
@erocarrera thoughts?

**Comment by kbandla** [comment]
Nice PR! I like the idea of this being its own project (for now), that uses pefile

**Comment by malwarefrank** [comment]
Thanks @kbandla, I do plan to release a separate project soon.  I have been tweaking the code for the past couple months.  Will post here and close this issue when I release it.

**Comment by malwarefrank** [comment]
I have separated out this functionality into its own project.  I am subclassing pefile.PE and took the opportunity to refactor the .NET parsing functionality.

See the code here https://github.com/malwarefrank/dnfile

or just install via pypi: pip install dnfile

**Pull request closed without merging**
