### PR TITLE
Fix imphash in python3

### PR DESCRIPTION
**Pull request by Rafiot**

### CODE REVIEW

**Comment by Rafiot** [comment]
No idea how to get travis to work but I tried on a few files, the imphash is consistant.

**Comment by stephenrauch** [comment]
How does this differ from #102 and/or #110?

**Comment by Rafiot** [comment]
None of them work with python 3.5.

**Comment by Rafiot** [comment]
Ans I fixed a bug.

**Comment by Rafiot** [comment]
I just ran this branch against *lots* of samples and it doesn't crash anymore.

**Comment by Rafiot** [comment]
@erocarrera: any change to get it merged?

**Comment by erocarrera** [comment]
Run all the regression test, seems to be all good! thanks!

**Comment by Rafiot** [comment]
\o/ thank you very much!

**Pull request merged**
