### PR TITLE
support for python 3.x

### PR DESCRIPTION
**Pull request by esnesenon**
Hey Ero,

Finally got around to creating the pull request, as we've talked.

Cheers,
Shay

### CODE REVIEW

**Comment by matysek** [comment]
I would love to see this pull request merged.

**Comment by esnesenon** [comment]
I actually completely forgot about this since then :>

Ero?

**Comment by jhg** [comment]
When pefile support Python 3?

**Comment by epu** [comment]
+1.

**Comment by obestwalter** [comment]
:+1:

**Comment by fpemud** [comment]
+1

**Comment by golubevmikhail** [comment]
Please, merge. I've spent needless time converting project to Py3.

**Comment by nyx0** [comment]
+1

**Comment by erocarrera** [comment]
pefile has been ported to work with Python 2 and Python 3.

**Comment by obestwalter** [comment]
Thanks @erocarrera

**Comment by golubevmikhail** [comment]
Many thanks!
5 марта 2016 г. 12:36 пользователь "Oliver Bestwalter" <
notifications@github.com> написал:

**Pull request closed without merging**
