### PR TITLE
Fixed overlay offset detection

### PR DESCRIPTION
**Pull request by Tim-Sobolev**
In case when are processed usual files, not dumps with fixed section table, section RVA <> section offset

### CODE REVIEW

**Comment by erocarrera** [comment]
Hi Tim, I find it hard to see how the code you modified could raise a PEFormatError exception. Can you provide with a file that reproduces the issue?

**Comment by Tim-Sobolev** [comment]
Hi. In case if something is wrong with sections table we can observe:

> Traceback (most recent call last):
>   File "D:\test_overlay.py", line 11, in <module>
>     ovr = pe.get_overlay()
>   File "C:\Python27\lib\site-packages\pefile.py", line 5487, in get_overlay
>     overlay_data_offset = self.get_overlay_data_start_offset()
>   File "C:\Python27\lib\site-packages\pefile.py", line 5476, in get_overlay_data_start_offset
>     (self.get_offset_from_rva(directory.VirtualAddress), directory.Size))
>   File "C:\Python27\lib\site-packages\pefile.py", line 4305, in get_offset_from_rva
>     raise PEFormatError('data at RVA can\'t be fetched. Corrupt header?')
> pefile.PEFormatError: "data at RVA can't be fetched. Corrupt header?"

**Comment by Tim-Sobolev** [comment]
Attached modified "write.exe" is executing properly but throw described exception without if no exception handler is used.

[write.zip](https://github.com/erocarrera/pefile/files/1193283/write.zip)

**Comment by Tim-Sobolev** [comment]
I have reworked commit to fix issues #104 and #127

**Comment by erocarrera** [comment]
Thanks, neat fix!

**Pull request merged**
